name: shoplistapp

description: A new Flutter project.

publish_to: 'none' 

version: 1.0.2+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  flutter_bloc: ^8.1.1
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  numberpicker: ^2.1.1
  flutter_slidable: ^2.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  firebase_storage: ^11.0.7
  file_picker: ^5.2.3
  flutter_svg: ^1.1.6
  motion_tab_bar_v2: ^0.2.3
  get_it: ^7.2.0
  injectable: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  injectable_generator: ^2.1.3
  build_runner: ^2.1.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/app_icon_2.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - images/icon/
    - images/list_icon/
    - images/photos/
    - images/icons/

  